#!/usr/bin/env python3
"""Generate core/model/.../NormalizationData.kt from Python's Unicode database.

Unicode normalization (NFC) has no Kotlin common API, and the simhash used for
dedup must produce the same answer on every platform, so the tables ship with
the app instead of depending on java.text.Normalizer / NSString / ICU.

Usage: pip install unicodedata2 && python3 tools/unicode/generate_normalization.py > core/model/src/commonMain/kotlin/xyz/mdhv/riverwip/model/NormalizationData.kt
Re-run when bumping the Unicode version; the JVM parity test
(NormalizationParityTest) compares the result against java.text.Normalizer.
"""
import sys

try:  # prefer the pip `unicodedata2` package: it tracks newer Unicode versions than the stdlib
    import unicodedata2 as ud
    SOURCE = "unicodedata2"
except ImportError:
    import unicodedata as ud
    SOURCE = "unicodedata"

HANGUL_S, HANGUL_E = 0xAC00, 0xD7A3
MAX_STR = 30000  # keep each literal well under the 65535-byte class-file constant limit

def chunks(entries, sep):
    out, cur, n = [], [], 0
    for e in entries:
        if n + len(e) + len(sep) > MAX_STR:
            out.append(sep.join(cur)); cur, n = [], 0
        cur.append(e); n += len(e) + len(sep)
    if cur: out.append(sep.join(cur))
    return out

def h(cp): return format(cp, "X")

ccc_ranges = []  # (start, end, class)
decomp = []      # cp=seq
pairs = []       # a,b=c
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF: continue
    ch = chr(cp)
    c = ud.combining(ch)
    if c:
        if ccc_ranges and ccc_ranges[-1][2] == c and ccc_ranges[-1][1] == cp - 1:
            ccc_ranges[-1] = (ccc_ranges[-1][0], cp, c)
        else:
            ccc_ranges.append((cp, cp, c))
    if HANGUL_S <= cp <= HANGUL_E: continue  # algorithmic
    nfd = ud.normalize("NFD", ch)
    if nfd != ch:
        decomp.append(h(cp) + "=" + " ".join(h(ord(x)) for x in nfd))
    raw = ud.decomposition(ch)
    if raw and not raw.startswith("<"):
        parts = raw.split()
        if len(parts) == 2 and ud.normalize("NFC", ch) == ch:
            pairs.append(f"{parts[0]},{parts[1]}={h(cp)}")

ccc = [f"{h(a)}-{h(b)}:{c}" if a != b else f"{h(a)}:{c}" for a, b, c in ccc_ranges]

def emit(name, parts, doc):
    print(f"    /** {doc} */")
    print(f"    val {name}: List<String> = listOf(")
    for p in parts: print(f'        "{p}",')
    print("    )\n")

print("// GENERATED by tools/unicode/generate_normalization.py -- do not edit by hand.")
print(f"// Unicode {ud.unidata_version} (Python {sys.version.split()[0]} {SOURCE}).")
print("package xyz.mdhv.riverwip.model\n")
print("/** Raw tables for [UnicodeNormalizer]; parsed lazily on first use. */")
print("internal object NormalizationData {")
print(f"    const val UNICODE_VERSION = \"{ud.unidata_version}\"\n")
emit("COMBINING_CLASSES", chunks(ccc, ";"), "`start[-end]:class` ranges of characters with a non-zero canonical combining class (hex), `;`-separated.")
emit("DECOMPOSITIONS", chunks(decomp, ";"), "`cp=seq` full canonical decompositions (hex, space-separated), excluding Hangul syllables (algorithmic).")
emit("COMPOSITIONS", chunks(pairs, ";"), "`first,second=composite` primary composites that survive NFC (composition exclusions already removed).")
print("}")
