package xyz.mdhv.riverwip.model

/**
 * Unicode canonical composition (NFC, UAX #15), replacing `java.text.Normalizer`.
 *
 * Kotlin has no common normalization API, and [Simhash] must hash a headline the
 * same way on every platform (the same story in two encodings has to dedup), so the
 * tables are shipped with the app ([NormalizationData], generated by
 * `tools/unicode/generate_normalization.py`) rather than borrowed from whichever
 * platform library happens to be underneath.
 *
 * Algorithm: canonical decomposition → canonical reordering by combining class →
 * canonical composition. Hangul syllables are handled arithmetically.
 */
internal object UnicodeNormalizer {

    // Hangul constants (Unicode §3.12)
    private const val S_BASE = 0xAC00
    private const val L_BASE = 0x1100
    private const val V_BASE = 0x1161
    private const val T_BASE = 0x11A7
    private const val L_COUNT = 19
    private const val V_COUNT = 21
    private const val T_COUNT = 28
    private const val N_COUNT = V_COUNT * T_COUNT
    private const val S_COUNT = L_COUNT * N_COUNT

    /** Everything below U+0300 is already NFC-stable when no combining mark follows it. */
    private const val FIRST_UNSTABLE = 0x300

    fun nfc(text: String): String {
        if (text.all { it.code < FIRST_UNSTABLE }) return text
        val cps = decompose(text)
        reorder(cps)
        return compose(cps)
    }

    // ---- lazily parsed tables -------------------------------------------

    private val combiningClass: Map<Int, Int> by lazy {
        val out = HashMap<Int, Int>()
        for (chunk in NormalizationData.COMBINING_CLASSES) for (entry in chunk.split(';')) {
            if (entry.isEmpty()) continue
            val (range, cls) = entry.split(':')
            val bounds = range.split('-')
            val from = bounds[0].toInt(16)
            val to = (bounds.getOrNull(1) ?: bounds[0]).toInt(16)
            for (cp in from..to) out[cp] = cls.toInt()
        }
        out
    }

    private val decomposition: Map<Int, IntArray> by lazy {
        val out = HashMap<Int, IntArray>()
        for (chunk in NormalizationData.DECOMPOSITIONS) for (entry in chunk.split(';')) {
            if (entry.isEmpty()) continue
            val (cp, seq) = entry.split('=')
            out[cp.toInt(16)] = seq.split(' ').map { it.toInt(16) }.toIntArray()
        }
        out
    }

    private val composition: Map<Long, Int> by lazy {
        val out = HashMap<Long, Int>()
        for (chunk in NormalizationData.COMPOSITIONS) for (entry in chunk.split(';')) {
            if (entry.isEmpty()) continue
            val (pair, composite) = entry.split('=')
            val (a, b) = pair.split(',')
            out[key(a.toInt(16), b.toInt(16))] = composite.toInt(16)
        }
        out
    }

    private fun key(first: Int, second: Int): Long = (first.toLong() shl 32) or second.toLong()

    private fun ccc(cp: Int): Int = combiningClass[cp] ?: 0

    // ---- steps ------------------------------------------------------------

    private fun decompose(text: String): MutableList<Int> {
        val out = ArrayList<Int>(text.length + 4)
        var i = 0
        while (i < text.length) {
            val c = text[i]
            var cp = c.code
            if (c.isHighSurrogate() && i + 1 < text.length && text[i + 1].isLowSurrogate()) {
                cp = 0x10000 + ((c.code - 0xD800) shl 10) + (text[i + 1].code - 0xDC00)
                i++
            }
            i++
            val s = cp - S_BASE
            if (s in 0 until S_COUNT) {
                out.add(L_BASE + s / N_COUNT)
                out.add(V_BASE + (s % N_COUNT) / T_COUNT)
                val t = s % T_COUNT
                if (t != 0) out.add(T_BASE + t)
                continue
            }
            val d = decomposition[cp]
            if (d != null) for (x in d) out.add(x) else out.add(cp)
        }
        return out
    }

    /** Stable sort of every run of non-starters by combining class. */
    private fun reorder(cps: MutableList<Int>) {
        var i = 0
        while (i < cps.size) {
            if (ccc(cps[i]) == 0) { i++; continue }
            var j = i
            while (j < cps.size && ccc(cps[j]) != 0) j++
            // insertion sort of cps[i until j]: runs are tiny in practice
            for (k in i + 1 until j) {
                val cp = cps[k]
                val cls = ccc(cp)
                var m = k - 1
                while (m >= i && ccc(cps[m]) > cls) { cps[m + 1] = cps[m]; m-- }
                cps[m + 1] = cp
            }
            i = j
        }
    }

    private fun composePair(first: Int, second: Int): Int {
        // Hangul L + V -> LV, LV + T -> LVT
        val l = first - L_BASE
        if (l in 0 until L_COUNT) {
            val v = second - V_BASE
            if (v in 0 until V_COUNT) return S_BASE + (l * V_COUNT + v) * T_COUNT
        }
        val s = first - S_BASE
        if (s in 0 until S_COUNT && s % T_COUNT == 0) {
            val t = second - T_BASE
            if (t in 1 until T_COUNT) return first + t
        }
        return composition[key(first, second)] ?: -1
    }

    private fun compose(cps: MutableList<Int>): String {
        if (cps.isEmpty()) return ""
        var starterPos = 0
        var starter = cps[0]
        var lastClass = ccc(starter)
        if (lastClass != 0) lastClass = 256 // an initial non-starter can never be composed onto
        var compPos = 1
        for (i in 1 until cps.size) {
            val ch = cps[i]
            val chClass = ccc(ch)
            val composite = composePair(starter, ch)
            if (composite >= 0 && (lastClass < chClass || lastClass == 0)) {
                cps[starterPos] = composite
                starter = composite
            } else {
                if (chClass == 0) {
                    starterPos = compPos
                    starter = ch
                }
                lastClass = chClass
                cps[compPos++] = ch
            }
        }
        val sb = StringBuilder(compPos)
        for (k in 0 until compPos) {
            val cp = cps[k]
            if (cp < 0x10000) sb.append(cp.toChar()) else {
                val v = cp - 0x10000
                sb.append((0xD800 + (v shr 10)).toChar()).append((0xDC00 + (v and 0x3FF)).toChar())
            }
        }
        return sb.toString()
    }
}
